layout_spectrum: 0.927855484082299
typography_spectrum: 0.17189143109900676
color:
  brandStrength: 0.22822467144375833
  lightness: 0.3750441479785276
  saturation: 0.39055824494505725
  rhythmicContrast: 0.6652850876662807
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: Architechtronica
title: Architechtronica
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/63f6e831-783f-4b23-994a-9a265ba0d14e.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/63f6e831-783f-4b23-994a-9a265ba0d14e.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: boundary architecture + technology
url: 'http://architechtronica.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/eed9a269-58c6-4801-8dd8-f594cf523499.png
github: true
